# .github/workflows/ci.yml
name: NethermindTest

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify the distribution of the JDK
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true

    - name: Install Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Install Sedge
      run: |
        curl -L https://github.com/NethermindEth/sedge/releases/download/v1.3.2/sedge-v1.3.2-linux-amd64  --output sedge
        sudo ls -l
        sudo mv sedge /usr/local/bin/sedge
        sudo chmod +x /usr/local/bin/sedge
        sedge version

    - name: Run Sedge to set up Nethermind
      run: |
        echo 'Running sedge...'
        sedge deps install >> sedge.logs
        sedge generate --logging none -p $HOME full-node \
        --map-all --no-mev-boost --no-validator \
        --network chiado -c lighthouse:sigp/lighthouse:latest \
        -e nethermind:nethermindeth/nethermind:master \
        --el-extra-flag Sync.NonValidatorNode=true \
        --el-extra-flag Sync.DownloadBodiesInFastSync=false \
        --el-extra-flag Sync.DownloadReceiptsInFastSync=false \
        --cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000/ >> sedge.logs
        sedge run -p . >> sedge.logs

    - name: Wait for Nethermind sync
      run: |
        echo 'Waiting for Nethermind to sync...'
        sleep 300 # Adjust sleep time as necessary
        until [ "$(curl -s -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' localhost:8545 | jq -r '.result')" = "false" ]; do
          echo 'Nethermind is still syncing...'
          sleep 60
        done
        echo 'Nethermind is synced.'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Install dependencies
      run: mvn install

    - name: Run JSON-RPC verification tests
      run: mvn -Dtest=JsonRpcVerificationTest test

    - name: Run JSON-RPC benchmark tests
      run: mvn -Dtest=JsonRpcBenchmarkTest test

    - name: Run extended JSON-RPC tests
      run: mvn -Dtest=JsonRpcExtendedTest test
